### ISSUE TITLE
See if we can find a user's messenger ID by its app ID ( and vice versa)

### ISSUE THREAD

**Issue by RJ-software-outsourcing** [StudioLoris/afuri-backend#1]
- [x] retrieve facebook oauth id from a user
- [x] retrieve messeger id of a user
- [x] get messenger id from oauth token
- [x] get oauth id from messenger

**Comment by Ningster** [comment]
## 官方文件
https://developers.facebook.com/docs/messenger-platform/identity/id-matching?locale=zh_TW

## 前提知識
* 應用程式範圍編號 - 系統針對特定的 Facebook 應用程式建立用戶編號
* 粉絲專頁範圍編號 - 系統便會針對與 Messenger Bot 相關聯的特定粉絲專頁建立用戶編號
**(因此，對同一用戶而言，不同溝通管道的用戶編號會有所不同。但透過Facebook API，相同企業管理平台所擁有的溝通管道可互相擷取用戶編號)**

## API 簡介，詳細請參考官方文件
1. 以 Messenger Bot 的用戶編號，取得應用程式用戶編號
```
GET /{user-id}/ids_for_apps
    ?access_token=[page_access_token]
    &appsecret_proof=[appsecret_proof]
```

2. 以應用程式用戶編號，取得Messenger Bot 的用戶編號
```
GET /{user-id}/ids_for_pages
    ?access_token=[app_access_token]
    &appsecret_proof=[appsecret_proof]
```
